services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  In2code\Luxletter\:
    resource: '../Classes/*'

  In2code\Luxletter\Command\ClearCommand:
    tags:
      - name: 'console.command'
        command: 'luxletter:clear'

  In2code\Luxletter\Command\ClearQueueCommand:
    tags:
      - name: 'console.command'
        command: 'luxletter:clearqueue'

  In2code\Luxletter\Command\CreateNewsletterFromOriginCommand:
    tags:
      - name: 'console.command'
        command: 'luxletter:createnewsletterfromorigin'

  In2code\Luxletter\Command\QueueCommand:
    tags:
      - name: 'console.command'
        command: 'luxletter:queue'

  In2code\Luxletter\Domain\Factory\UserFactory:
    public: true

  In2code\Luxletter\Domain\Service\Parsing\Newsletter:
    public: true

  In2code\Luxletter\Domain\Service\QueueService:
    public: true

  In2code\Luxletter\Middleware\LuxletterLink:
    public: true
